[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=Xvfb :99 -screen 0 1280x720x24 -ac +extension RANDR
autostart=true
autorestart=true
environment=DISPLAY=:99

[program:freerdp]
command=xfreerdp /v:%%(ENV_TARGET_HOST)s:%%(ENV_TARGET_PORT)s /u:%%(ENV_TARGET_USER)s /p:%%(ENV_TARGET_PASS)s /size:1280x720 /cert-ignore +fonts +clipboard /sound:sys:pulse
autostart=true
autorestart=true

[program:x11vnc]
command=x11vnc -display :99 -forever -nopw -quiet -listen 0.0.0.0 -xkb
autostart=true
autorestart=true

[program:websockify]
command=websockify --web /usr/share/novnc 8081 localhost:5900
autostart=true
autorestart=true

[program:gstreamer]
command=python3 /gst-pipeline.py
autostart=true
autorestart=true
environment=DISPLAY=:99
